# Generated by Django 6.0.5 on 2026-05-29 22:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='رسته کاری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رسته کاری',
                'verbose_name_plural': 'رسته های کاری',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('TECHNICAL', 'دفتر فنی'), ('WAREHOUSE', 'انباردار')], help_text='دفتر فنی = مهندسین و کارشناسان | انباردار = مسئول انبار کارگاه', max_length=20, null=True, verbose_name='نقش کاربری')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام پیمانکار')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی پیمانکار')),
            ],
            options={
                'verbose_name': 'پیمانکار',
                'verbose_name_plural': 'پیمانکاران',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='سایز')),
                ('material_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس متریال')),
                ('thickness', models.CharField(blank=True, max_length=100, null=True, verbose_name='ضخامت')),
                ('unit', models.CharField(choices=[('KG', 'کیلوگرم'), ('M', 'متر'), ('SQM', 'متر مربع'), ('PCS', 'عدد')], max_length=10, verbose_name='واحد اندازه گیری')),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد پرتی مجاز')),
                ('work_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='balance.workcategory', verbose_name='رسته کاری')),
            ],
            options={
                'verbose_name': 'کالا / متریال',
                'verbose_name_plural': 'کالاها / متریال ها',
            },
        ),
        migrations.CreateModel(
            name='TechnicalOfficeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار کار تایید شده')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('contract_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع قرارداد')),
                ('approval_date', models.DateField(db_index=True, verbose_name='تاریخ تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='balance.contractor', verbose_name='پیمانکار')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='balance.materialitem', verbose_name='نوع متریال')),
            ],
            options={
                'verbose_name': 'تاییدیه عملکرد دفتر فنی',
                'verbose_name_plural': 'تاییدیه\u200cهای عملکرد دفتر فنی',
                'indexes': [models.Index(fields=['contractor', 'material'], name='balance_tec_contrac_7928e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'ورود متریال به انبار'), ('OUT', 'خروج متریال به پیمانکار')], db_index=True, max_length=3, verbose_name='نوع تراکنش')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار')),
                ('bill_of_lading', models.CharField(blank=True, help_text='شماره بارنامه حمل متریال (فقط برای تراکنش ورود).', max_length=100, null=True, verbose_name='شماره بارنامه')),
                ('contractor_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پیمانکار')),
                ('contractor_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی پیمانکار')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('contract_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع قرارداد')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
                ('contractor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.contractor', verbose_name='پیمانکار (خودکار)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='balance.materialitem', verbose_name='متریال')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش های انبار',
                'indexes': [models.Index(fields=['contractor', 'material'], name='balance_war_contrac_cd244c_idx'), models.Index(fields=['transaction_type', 'date'], name='balance_war_transac_2107fd_idx')],
            },
        ),
    ]
