# Generated by Django 6.0.5 on 2026-05-30 09:53

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalofficeapproval',
            name='approval_date',
            field=django_jalali.db.models.jDateField(db_index=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='date',
            field=django_jalali.db.models.jDateField(db_index=True, verbose_name='تاریخ'),
        ),
    ]
