# Generated by Django 6.0.5 on 2026-05-30 10:02

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_technicalofficeapproval_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalofficeapproval',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم'),
        ),
    ]
