# Generated by Django 6.0.5 on 2026-06-06 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_alter_technicalofficeapproval_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitem',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='اگر موجودی انبار از این مقدار کمتر شود، هشدار صادر می\u200cشود. مقدار ۰ = غیرفعال.', max_digits=12, verbose_name='آستانه موجودی بحرانی'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'ویرایش'), ('DELETE', 'حذف')], db_index=True, max_length=10, verbose_name='نوع عملیات')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='نام مدل')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه رکورد')),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='شرح رکورد')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='جزئیات تغییرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ تغییرات',
                'verbose_name_plural': 'لاگ\u200cهای تغییرات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'model_name'], name='balance_aud_timesta_c11ea4_idx'), models.Index(fields=['user', '-timestamp'], name='balance_aud_user_id_943783_idx')],
            },
        ),
    ]
