# Generated by Django 6.0.5 on 2026-06-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_materialitem_low_stock_threshold_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='contractor_first_name',
        ),
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='contractor_last_name',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='توسط سیستم و به صورت اتمیک به\u200cروز می\u200cشود.', max_digits=12, verbose_name='موجودی لحظه\u200cای'),
        ),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='balance.contractor', verbose_name='پیمانکار'),
        ),
    ]
