# Generated by Django 6.0.5 on 2026-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_remove_warehousetransaction_contractor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransaction',
            name='bill_of_lading_image',
            field=models.TextField(blank=True, help_text='تصویر بارنامه به صورت کدگذاری شده Base64.', null=True, verbose_name='تصویر بارنامه اسکن شده'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='exit_document_image',
            field=models.TextField(blank=True, help_text='تصویر برگه خروج به صورت کدگذاری شده Base64.', null=True, verbose_name='تصویر برگه خروج اسکن شده'),
        ),
    ]
