# Generated by Django 6.0.5 on 2026-06-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_warehousetransaction_bill_of_lading_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMaterialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('contract_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع قرارداد')),
                ('total_issued', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='کل صادر شده')),
                ('approved_work', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='کار تایید شده')),
                ('allowed_waste', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='پرت مجاز')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='موازنه انحراف')),
                ('balance_label', models.CharField(db_index=True, max_length=100, verbose_name='وضعیت موازنه')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_balances', to='balance.contractor', verbose_name='پیمانکار')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_balances', to='balance.materialitem', verbose_name='نوع متریال')),
            ],
            options={
                'verbose_name': 'موازنه متریال کل کارگاه',
                'verbose_name_plural': 'موازنه متریال کل کارگاه',
                'indexes': [models.Index(fields=['contractor', 'material'], name='balance_glo_contrac_18037c_idx'), models.Index(fields=['contract_number'], name='balance_glo_contrac_f88667_idx'), models.Index(fields=['balance_label'], name='balance_glo_balance_047a03_idx')],
                'unique_together': {('contractor', 'material', 'contract_number', 'contract_subject')},
            },
        ),
    ]
