# Generated by Django 6.0.5 on 2026-06-18 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_globalmaterialbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('SUCCESS', 'موفق'), ('FAILURE', 'خطا')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('progress', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('eta', models.IntegerField(default=0, verbose_name='زمان باقی\u200cمانده (ثانیه)')),
                ('file_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس دانلود فایل')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تسک خروجی فایل',
                'verbose_name_plural': 'تسک\u200cهای خروجی فایل',
                'ordering': ['-created_at'],
            },
        ),
    ]
