# Generated by Django 6.0.5 on 2026-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_exporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='task_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF')], default='excel', max_length=10, verbose_name='نوع فایل'),
        ),
    ]
